function createfigure1(xvector1, ymatrix1)
%CREATEFIGURE1(XVECTOR1,YMATRIX1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 25-Apr-2012 16:18:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTick',[3 7 11 15 19 23 27 31 35 39 43 47 51]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 54]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 50]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'Parent',axes1);
set(bar1(2),'FaceColor',[0.6 0.2 0]);
set(bar1(3),'FaceColor',[0 0.498039215686275 0]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.731339285714285 0.759003732849074 0.160714285714286 0.146892655367232]);

