function createfigure(xvector1, yvector1)
%CREATEFIGURE(XVECTOR1,YVECTOR1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 25-Apr-2012 16:04:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTick',[3 7 11 15 19 23 27 31 35 39 43 47 51]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 54]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 50]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create bar
bar(xvector1,yvector1);

